// Palestinian cities (governorate centers) and their areas/neighborhoods/towns,
// bilingual (Arabic + English). Used by the manual location picker so customers
// can choose a City + Area instead of free-typing, and by technicians to define
// their coverage. Each city carries coordinates so the booking can be matched
// to the nearest technician even without browser geolocation.
// The "areas" of every city include its main neighborhoods plus the well-known
// towns, villages and refugee camps of the governorate.
export const PALESTINE_LOCATIONS = [
    {
        nameAr: "رام الله والبيرة", nameEn: "Ramallah & Al-Bireh", lat: 31.9029, lng: 35.2062,
        areas: [
            { nameAr: "وسط البلد", nameEn: "Downtown" },
            { nameAr: "الطيرة", nameEn: "Al-Tira" },
            { nameAr: "الماصيون", nameEn: "Al-Masyoun" },
            { nameAr: "عين مصباح", nameEn: "Ein Misbah" },
            { nameAr: "البالوع", nameEn: "Al-Balou" },
            { nameAr: "الإرسال", nameEn: "Al-Irsal" },
            { nameAr: "أم الشرايط", nameEn: "Umm ash-Sharayit" },
            { nameAr: "بيتونيا", nameEn: "Beitunia" },
            { nameAr: "بيرزيت", nameEn: "Birzeit" },
            { nameAr: "سلواد", nameEn: "Silwad" },
            { nameAr: "دير دبوان", nameEn: "Deir Dibwan" },
            { nameAr: "الطيبة", nameEn: "Taybeh" },
            { nameAr: "ترمسعيا", nameEn: "Turmus Ayya" },
            { nameAr: "سنجل", nameEn: "Sinjil" },
            { nameAr: "نعلين", nameEn: "Ni'lin" },
            { nameAr: "مخيم الأمعري", nameEn: "Al-Am'ari Camp" },
            { nameAr: "مخيم الجلزون", nameEn: "Al-Jalazone Camp" },
            { nameAr: "مخيم قلنديا", nameEn: "Qalandiya Camp" },
        ],
    },
    {
        nameAr: "نابلس", nameEn: "Nablus", lat: 32.2211, lng: 35.2544,
        areas: [
            { nameAr: "البلدة القديمة", nameEn: "Old City" },
            { nameAr: "رفيديا", nameEn: "Rafidia" },
            { nameAr: "المخفية", nameEn: "Al-Makhfeyya" },
            { nameAr: "جبل النار", nameEn: "Mount Ebal Side" },
            { nameAr: "عسكر", nameEn: "Askar" },
            { nameAr: "بيت وزن", nameEn: "Beit Wazan" },
            { nameAr: "مخيم بلاطة", nameEn: "Balata Camp" },
            { nameAr: "حوارة", nameEn: "Huwwara" },
            { nameAr: "بيتا", nameEn: "Beita" },
            { nameAr: "عصيرة الشمالية", nameEn: "Asira ash-Shamaliya" },
            { nameAr: "سبسطية", nameEn: "Sebastia" },
            { nameAr: "بورين", nameEn: "Burin" },
            { nameAr: "عقربا", nameEn: "Aqraba" },
            { nameAr: "بيت فوريك", nameEn: "Beit Furik" },
            { nameAr: "قوصين", nameEn: "Qusin" },
        ],
    },
    {
        nameAr: "الخليل", nameEn: "Hebron", lat: 31.5298, lng: 35.0998,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "الحرس", nameEn: "Al-Haras" },
            { nameAr: "عين سارة", nameEn: "Ein Sara" },
            { nameAr: "وادي الهرية", nameEn: "Wadi Al-Hariya" },
            { nameAr: "الجامعة", nameEn: "University Area" },
            { nameAr: "دورا", nameEn: "Dura" },
            { nameAr: "يطا", nameEn: "Yatta" },
            { nameAr: "حلحول", nameEn: "Halhul" },
            { nameAr: "بيت أمر", nameEn: "Beit Ummar" },
            { nameAr: "إذنا", nameEn: "Idhna" },
            { nameAr: "ترقوميا", nameEn: "Tarqumiya" },
            { nameAr: "الظاهرية", nameEn: "Adh-Dhahiriya" },
            { nameAr: "السموع", nameEn: "As-Samu" },
            { nameAr: "بني نعيم", nameEn: "Bani Na'im" },
            { nameAr: "سعير", nameEn: "Sa'ir" },
            { nameAr: "مخيم الفوار", nameEn: "Al-Fawwar Camp" },
            { nameAr: "مخيم العروب", nameEn: "Al-Arroub Camp" },
        ],
    },
    {
        nameAr: "القدس", nameEn: "Jerusalem", lat: 31.7683, lng: 35.2137,
        areas: [
            { nameAr: "البلدة القديمة", nameEn: "Old City" },
            { nameAr: "بيت حنينا", nameEn: "Beit Hanina" },
            { nameAr: "شعفاط", nameEn: "Shuafat" },
            { nameAr: "العيسوية", nameEn: "Issawiya" },
            { nameAr: "صور باهر", nameEn: "Sur Baher" },
            { nameAr: "سلوان", nameEn: "Silwan" },
            { nameAr: "الطور", nameEn: "At-Tur" },
            { nameAr: "الرام", nameEn: "Ar-Ram" },
            { nameAr: "كفر عقب", nameEn: "Kafr Aqab" },
            { nameAr: "قلنديا", nameEn: "Qalandiya" },
            { nameAr: "أبو ديس", nameEn: "Abu Dis" },
            { nameAr: "العيزرية", nameEn: "Al-Eizariya" },
            { nameAr: "عناتا", nameEn: "Anata" },
            { nameAr: "حزما", nameEn: "Hizma" },
            { nameAr: "قطنة", nameEn: "Qatanna" },
            { nameAr: "بدو", nameEn: "Biddu" },
        ],
    },
    {
        nameAr: "بيت لحم", nameEn: "Bethlehem", lat: 31.7058, lng: 35.2007,
        areas: [
            { nameAr: "وسط البلد", nameEn: "Downtown" },
            { nameAr: "بيت جالا", nameEn: "Beit Jala" },
            { nameAr: "بيت ساحور", nameEn: "Beit Sahour" },
            { nameAr: "الدوحة", nameEn: "Ad-Doha" },
            { nameAr: "الخضر", nameEn: "Al-Khader" },
            { nameAr: "العبيدية", nameEn: "Al-Ubeidiya" },
            { nameAr: "تقوع", nameEn: "Tuqu'" },
            { nameAr: "بتير", nameEn: "Battir" },
            { nameAr: "نحالين", nameEn: "Nahhalin" },
            { nameAr: "مخيم الدهيشة", nameEn: "Dheisheh Camp" },
            { nameAr: "مخيم عايدة", nameEn: "Aida Camp" },
        ],
    },
    {
        nameAr: "جنين", nameEn: "Jenin", lat: 32.4610, lng: 35.2952,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "الباشا", nameEn: "Al-Basha" },
            { nameAr: "الزهراء", nameEn: "Al-Zahraa" },
            { nameAr: "مخيم جنين", nameEn: "Jenin Camp" },
            { nameAr: "قباطية", nameEn: "Qabatiya" },
            { nameAr: "يعبد", nameEn: "Ya'bad" },
            { nameAr: "عرابة", nameEn: "Arraba" },
            { nameAr: "ميثلون", nameEn: "Meithalun" },
            { nameAr: "برقين", nameEn: "Burqin" },
            { nameAr: "الزبابدة", nameEn: "Az-Zababdeh" },
            { nameAr: "سيلة الظهر", nameEn: "Silat adh-Dhahr" },
            { nameAr: "جبع", nameEn: "Jaba'" },
        ],
    },
    {
        nameAr: "طولكرم", nameEn: "Tulkarm", lat: 32.3136, lng: 35.0275,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "الشويكة", nameEn: "Shweika" },
            { nameAr: "ذنابة", nameEn: "Dhinnaba" },
            { nameAr: "مخيم طولكرم", nameEn: "Tulkarm Camp" },
            { nameAr: "عنبتا", nameEn: "Anabta" },
            { nameAr: "بلعا", nameEn: "Bal'a" },
            { nameAr: "دير الغصون", nameEn: "Deir al-Ghusun" },
            { nameAr: "عتيل", nameEn: "Attil" },
            { nameAr: "علار", nameEn: "Allar" },
            { nameAr: "قفين", nameEn: "Qaffin" },
            { nameAr: "زيتا", nameEn: "Zeita" },
        ],
    },
    {
        nameAr: "قلقيلية", nameEn: "Qalqilya", lat: 32.1950, lng: 34.9814,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "كفر سابا", nameEn: "Kafr Saba" },
            { nameAr: "النقار", nameEn: "Al-Naqqar" },
            { nameAr: "عزون", nameEn: "Azzun" },
            { nameAr: "حبلة", nameEn: "Habla" },
            { nameAr: "جيوس", nameEn: "Jayyous" },
            { nameAr: "كفر ثلث", nameEn: "Kafr Thulth" },
            { nameAr: "كفر قدوم", nameEn: "Kafr Qaddum" },
        ],
    },
    {
        nameAr: "أريحا", nameEn: "Jericho", lat: 31.8560, lng: 35.4443,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "عقبة جبر", nameEn: "Aqabat Jabr" },
            { nameAr: "النويعمة", nameEn: "An-Nuwei'ma" },
            { nameAr: "عين السلطان", nameEn: "Ein as-Sultan" },
            { nameAr: "العوجا", nameEn: "Al-Auja" },
            { nameAr: "الجفتلك", nameEn: "Al-Jiftlik" },
            { nameAr: "فصايل", nameEn: "Fasayil" },
        ],
    },
    {
        nameAr: "سلفيت", nameEn: "Salfit", lat: 32.0850, lng: 35.1814,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "المنطقة الغربية", nameEn: "Western Area" },
            { nameAr: "بديا", nameEn: "Biddya" },
            { nameAr: "دير استيا", nameEn: "Deir Istiya" },
            { nameAr: "كفل حارس", nameEn: "Kifl Hares" },
            { nameAr: "حارس", nameEn: "Haris" },
            { nameAr: "الزاوية", nameEn: "Az-Zawiya" },
            { nameAr: "بروقين", nameEn: "Bruqin" },
        ],
    },
    {
        nameAr: "طوباس", nameEn: "Tubas", lat: 32.3228, lng: 35.3697,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "تياسير", nameEn: "Tayasir" },
            { nameAr: "طمون", nameEn: "Tammun" },
            { nameAr: "عقابا", nameEn: "Aqqaba" },
            { nameAr: "مخيم الفارعة", nameEn: "Al-Far'a Camp" },
            { nameAr: "بردلة", nameEn: "Bardala" },
        ],
    },
    {
        nameAr: "غزة", nameEn: "Gaza", lat: 31.5000, lng: 34.4667,
        areas: [
            { nameAr: "الرمال", nameEn: "Al-Rimal" },
            { nameAr: "الشجاعية", nameEn: "Al-Shujaiya" },
            { nameAr: "الزيتون", nameEn: "Al-Zaytoun" },
            { nameAr: "تل الهوا", nameEn: "Tal Al-Hawa" },
            { nameAr: "الصبرة", nameEn: "As-Sabra" },
            { nameAr: "الدرج", nameEn: "Ad-Daraj" },
            { nameAr: "التفاح", nameEn: "At-Tuffah" },
            { nameAr: "الشيخ رضوان", nameEn: "Sheikh Radwan" },
            { nameAr: "النصر", nameEn: "An-Nasr" },
            { nameAr: "مخيم الشاطئ", nameEn: "Ash-Shati Camp" },
        ],
    },
    {
        nameAr: "خان يونس", nameEn: "Khan Yunis", lat: 31.3462, lng: 34.3025,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "المخيم", nameEn: "Camp Area" },
            { nameAr: "القرارة", nameEn: "Al-Qarara" },
            { nameAr: "بني سهيلا", nameEn: "Bani Suheila" },
            { nameAr: "عبسان الكبيرة", nameEn: "Abasan al-Kabira" },
            { nameAr: "خزاعة", nameEn: "Khuza'a" },
            { nameAr: "المواصي", nameEn: "Al-Mawasi" },
        ],
    },
    {
        nameAr: "رفح", nameEn: "Rafah", lat: 31.2842, lng: 34.2534,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "تل السلطان", nameEn: "Tal Al-Sultan" },
            { nameAr: "الشابورة", nameEn: "Ash-Shaboura" },
            { nameAr: "الشوكة", nameEn: "Ash-Shawka" },
            { nameAr: "مخيم يبنا", nameEn: "Yibna Camp" },
        ],
    },
    {
        nameAr: "دير البلح", nameEn: "Deir al-Balah", lat: 31.4178, lng: 34.3503,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "النصيرات", nameEn: "An-Nuseirat" },
            { nameAr: "البريج", nameEn: "Al-Bureij" },
            { nameAr: "المغازي", nameEn: "Al-Maghazi" },
            { nameAr: "الزوايدة", nameEn: "Az-Zawayda" },
            { nameAr: "المصدر", nameEn: "Al-Musaddar" },
            { nameAr: "وادي السلقا", nameEn: "Wadi as-Salqa" },
        ],
    },
    {
        nameAr: "جباليا", nameEn: "Jabalia", lat: 31.5292, lng: 34.4839,
        areas: [
            { nameAr: "وسط المدينة", nameEn: "City Center" },
            { nameAr: "المخيم", nameEn: "Camp Area" },
            { nameAr: "بيت لاهيا", nameEn: "Beit Lahia" },
            { nameAr: "بيت حانون", nameEn: "Beit Hanoun" },
            { nameAr: "النزلة", nameEn: "An-Nazla" },
            { nameAr: "تل الزعتر", nameEn: "Tal az-Za'atar" },
        ],
    },
];

// Return the city object matching an English or Arabic name.
export function findCity(name) {
    if (!name) return null;
    return PALESTINE_LOCATIONS.find(
        (c) => c.nameEn === name || c.nameAr === name
    ) || null;
}
